---
- name: Configuração do Kubernetes
  block:
    - name: Cria arquivos do sysctl.d & modules-load.d config
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0644
      loop:
        - /etc/modules-load.d/
        - /etc/sysctl.d/
      changed_when: False

    - name: Configuração de Module Kernel
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        mode: 0644
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          br_netfilter
          overlay

    - name: Configuração de Sysctl
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        mode: 0644
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
